export const styles = {
  app: {
    position: "fixed", inset: 0, overflow: "hidden",
    fontFamily: "'Avenir Next','Segoe UI',system-ui,sans-serif",
    background: "#23262B", color: "#EDEAE3",
  },
  canvasWrap: { position: "absolute", inset: 0 },
  topBar: {
    position: "absolute", top: 0, left: 0, right: 0,
    padding: "12px 14px 8px",
    display: "flex", flexDirection: "column", gap: 9,
    background: "linear-gradient(180deg, rgba(20,22,26,.88), rgba(20,22,26,0))",
    pointerEvents: "none",
  },
  wordmark: { display: "flex", alignItems: "center", gap: 7, pointerEvents: "auto" },
  wordmarkSerif: {
    fontFamily: "Georgia,'Times New Roman',serif", fontStyle: "italic",
    fontSize: 22, letterSpacing: 0.3, color: "#F2EEE6",
  },
  wordmarkBadge: {
    fontSize: 10, fontWeight: 700, letterSpacing: 2,
    border: "1px solid", borderRadius: 3, padding: "1px 5px",
  },
  dims: { fontSize: 11, color: "rgba(237,234,227,.55)", marginLeft: 4, letterSpacing: 0.5 },
  photoBtn: {
    marginLeft: "auto", background: "rgba(40,44,50,.95)", color: "#E8E4DB",
    border: "1px solid rgba(255,255,255,.18)", borderRadius: 8,
    padding: "6px 11px", fontSize: 12, cursor: "pointer", whiteSpace: "nowrap",
  },
  fsBtn: {
    background: "rgba(40,44,50,.95)", color: "#E8E4DB",
    border: "1px solid rgba(255,255,255,.18)", borderRadius: 8,
    padding: "6px 11px", fontSize: 12, cursor: "pointer", whiteSpace: "nowrap",
    flexShrink: 0,
  },
  controlRow: {
    display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap",
    pointerEvents: "auto",
  },
  seg: {
    display: "flex", border: "1px solid rgba(255,255,255,.16)",
    borderRadius: 10, overflow: "hidden", flexShrink: 0,
  },
  segBtn: {
    background: "rgba(30,33,38,.9)", color: "rgba(237,234,227,.7)",
    border: "none", padding: "8px 16px", fontSize: 13, fontWeight: 700,
    letterSpacing: 0.5, cursor: "pointer", whiteSpace: "nowrap",
  },
  segBtnSm: {
    background: "rgba(30,33,38,.9)", color: "rgba(237,234,227,.7)",
    border: "none", padding: "7px 11px", fontSize: 12, fontWeight: 700,
    letterSpacing: 0.3, cursor: "pointer", whiteSpace: "nowrap",
  },
  presetRow: {
    display: "flex", gap: 8, overflowX: "auto", paddingBottom: 4,
    pointerEvents: "auto", scrollbarWidth: "none",
  },
  presetChip: {
    flexShrink: 0, display: "flex", alignItems: "center", gap: 7,
    background: "rgba(38,42,48,.92)", color: "#E8E4DB",
    border: "1px solid rgba(255,255,255,.12)", borderRadius: 999,
    padding: "7px 13px", fontSize: 13, cursor: "pointer", whiteSpace: "nowrap",
  },
  dotRow: { display: "flex", gap: 2 },
  dot: { width: 9, height: 9, borderRadius: "50%", border: "1px solid rgba(0,0,0,.25)" },
  modeSeg: {
    marginLeft: "auto", display: "flex",
    border: "1px solid rgba(255,255,255,.18)", borderRadius: 9,
    overflow: "hidden", flexShrink: 0, alignSelf: "center",
  },
  modeSegBtn: {
    background: "rgba(30,33,38,.9)", color: "rgba(237,234,227,.7)",
    border: "none", padding: "7px 12px", fontSize: 12, fontWeight: 700,
    letterSpacing: 0.3, cursor: "pointer", whiteSpace: "nowrap",
  },
  undoBtn: {
    background: "transparent", color: "#EDEAE3",
    border: "1px solid rgba(255,255,255,.18)", borderRadius: 8,
    padding: "6px 10px", fontSize: 12, fontWeight: 600, cursor: "pointer",
    whiteSpace: "nowrap", flexShrink: 0,
  },
  selBar: {
    position: "absolute", left: "50%", transform: "translateX(-50%)",
    bottom: 142, display: "flex", alignItems: "center", gap: 8,
    background: "rgba(28,31,36,.95)", border: "1px solid rgba(255,255,255,.14)",
    borderRadius: 12, padding: "8px 12px", maxWidth: "94vw",
    overflowX: "auto", scrollbarWidth: "none",
  },
  selLabel: { fontSize: 13, fontWeight: 600, whiteSpace: "nowrap", color: "#F2EEE6" },
  selBtn: {
    background: "transparent", border: "1px solid rgba(255,255,255,.18)",
    color: "#EDEAE3", borderRadius: 8, padding: "5px 10px",
    fontSize: 13, cursor: "pointer", whiteSpace: "nowrap", flexShrink: 0,
  },
  selDivider: { width: 1, height: 22, background: "rgba(255,255,255,.15)", flexShrink: 0 },
  lightLabel: {
    fontSize: 11, fontWeight: 700, letterSpacing: 1, textTransform: "uppercase",
    color: "rgba(237,234,227,.6)", flexShrink: 0,
  },
  lightSlider: { width: 92, flexShrink: 0, minWidth: 0 },
  lightVal: { fontSize: 12, fontWeight: 600, width: 38, color: "#F4E9D2", flexShrink: 0 },
  swatchSm: {
    width: 22, height: 22, borderRadius: "50%", border: "none",
    cursor: "pointer", flexShrink: 0, padding: 0,
  },
  bottom: {
    position: "absolute", left: 0, right: 0, bottom: 0,
    background: "linear-gradient(0deg, rgba(20,22,26,.95) 65%, rgba(20,22,26,0))",
    padding: "8px 12px calc(10px + env(safe-area-inset-bottom))",
  },
  tabRow: {
    display: "flex", gap: 10, marginBottom: 8, alignItems: "center",
    overflowX: "auto", scrollbarWidth: "none",
  },
  tab: {
    background: "transparent", color: "rgba(237,234,227,.65)",
    border: "none", borderBottom: "2px solid transparent",
    padding: "4px 2px", fontSize: 13, fontWeight: 600, letterSpacing: 0.4,
    cursor: "pointer", whiteSpace: "nowrap", flexShrink: 0,
  },
  catalogRow: {
    display: "flex", alignItems: "center", gap: 8, overflowX: "auto",
    paddingBottom: 2, scrollbarWidth: "none",
  },
  catBtn: {
    flexShrink: 0, display: "flex", alignItems: "center", gap: 6,
    background: "rgba(40,44,50,.95)", color: "#E8E4DB",
    border: "1px solid rgba(255,255,255,.12)", borderRadius: 10,
    padding: "9px 13px", fontSize: 13, cursor: "pointer", whiteSpace: "nowrap",
  },
  catPlus: { fontWeight: 700, fontSize: 15, lineHeight: 1 },
  stylePanel: { display: "flex", flexDirection: "column", gap: 9, paddingBottom: 2 },
  styleGroup: { display: "flex", alignItems: "center", gap: 10 },
  styleLabel: {
    fontSize: 12, fontWeight: 700, letterSpacing: 1.2, textTransform: "uppercase",
    color: "rgba(237,234,227,.6)", width: 60, flexShrink: 0,
  },
  finishRow: { display: "flex", gap: 6, overflowX: "auto", scrollbarWidth: "none" },
  finishChip: {
    flexShrink: 0, background: "rgba(40,44,50,.95)", color: "#E8E4DB",
    border: "1px solid rgba(255,255,255,.14)", borderRadius: 8,
    padding: "6px 11px", fontSize: 12, cursor: "pointer", whiteSpace: "nowrap",
  },
  swatchRow: { display: "flex", gap: 8, overflowX: "auto", scrollbarWidth: "none" },
  swatchLg: {
    width: 32, height: 32, borderRadius: 8, border: "none",
    cursor: "pointer", flexShrink: 0, padding: 0,
  },
  sliderGroup: { display: "flex", alignItems: "center", gap: 10 },
  slider: { flex: 1, minWidth: 0 },
  sliderVal: { fontSize: 13, fontWeight: 600, width: 48, textAlign: "right", color: "#F4E9D2" },
  designHeader: { display: "flex", alignItems: "center", gap: 10 },
  saveDesignBtn: {
    background: "transparent", border: "1px solid", borderRadius: 9,
    padding: "7px 13px", fontSize: 13, fontWeight: 700, cursor: "pointer",
    whiteSpace: "nowrap",
  },
  storageWarn: { fontSize: 11, color: "#E07856" },
  emptyDesigns: { fontSize: 12.5, color: "rgba(237,234,227,.55)", lineHeight: 1.45 },
  designList: {
    display: "flex", flexDirection: "column", gap: 6,
    maxHeight: 150, overflowY: "auto",
  },
  designRow: {
    display: "flex", alignItems: "center", gap: 8,
    background: "rgba(40,44,50,.7)", borderRadius: 9, padding: "6px 10px",
  },
  designName: { fontSize: 12.5, fontWeight: 600, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  designMeta: { fontSize: 11, color: "rgba(237,234,227,.5)", whiteSpace: "nowrap", marginLeft: "auto" },
  editorOverlay: {
    position: "fixed", inset: 0, zIndex: 100,
    background: "rgba(10,12,15,.88)", display: "flex",
    alignItems: "center", justifyContent: "center", padding: 16,
  },
  editorPanel: {
    width: "min(960px, 96vw)", height: "min(640px, 92vh)",
    background: "#23262B", borderRadius: 14,
    border: "1px solid rgba(255,255,255,.12)",
    display: "flex", flexDirection: "column", overflow: "hidden",
  },
  editorHeader: {
    display: "flex", alignItems: "center", justifyContent: "space-between",
    padding: "14px 18px", borderBottom: "1px solid rgba(255,255,255,.1)",
  },
  editorTitle: { display: "block", fontSize: 18, fontWeight: 700, color: "#F2EEE6" },
  editorSubtitle: { display: "block", fontSize: 12, color: "rgba(237,234,227,.55)", marginTop: 2 },
  editorClose: {
    background: "transparent", border: "none", color: "#EDEAE3",
    fontSize: 18, cursor: "pointer", padding: 4,
  },
  editorBody: { flex: 1, display: "flex", minHeight: 0 },
  editorMainCol: { flex: 1, display: "flex", flexDirection: "column", minWidth: 0, minHeight: 0 },
  editorPlanRow: { display: "flex", flex: 1, minHeight: 160, borderTop: "1px solid rgba(255,255,255,.08)" },
  editorCanvas: { flex: 1, minWidth: 0, background: "#1a1d22" },
  editorSidebar: {
    width: 280, borderLeft: "1px solid rgba(255,255,255,.1)",
    padding: 14, overflowY: "auto", display: "flex", flexDirection: "column", gap: 16,
  },
  editorSection: { display: "flex", flexDirection: "column", gap: 8 },
  editorSectionTitle: {
    fontSize: 11, fontWeight: 700, letterSpacing: 1, textTransform: "uppercase",
    color: "rgba(237,234,227,.55)",
  },
  editorPartList: { display: "flex", flexDirection: "column", gap: 6 },
  editorPartBtn: {
    textAlign: "left", background: "rgba(40,44,50,.95)", color: "#E8E4DB",
    border: "1px solid rgba(255,255,255,.14)", borderRadius: 8,
    padding: "8px 10px", fontSize: 13, cursor: "pointer",
  },
  editorAddRow: { display: "flex", gap: 8 },
  editorAddBtn: {
    flex: 1, background: "rgba(30,33,38,.9)", color: "#EDEAE3",
    border: "1px dashed rgba(255,255,255,.2)", borderRadius: 8,
    padding: "7px 8px", fontSize: 12, cursor: "pointer",
  },
  editorShapeGrid: { display: "flex", flexWrap: "wrap", gap: 6 },
  editorShapeBtn: {
    background: "rgba(40,44,50,.95)", color: "#E8E4DB",
    border: "1px solid rgba(255,255,255,.14)", borderRadius: 8,
    padding: "6px 10px", fontSize: 11, cursor: "pointer", whiteSpace: "nowrap",
  },
  editorDimRow: { display: "flex", alignItems: "center", gap: 8 },
  editorDimLabel: { width: 72, fontSize: 12, color: "rgba(237,234,227,.65)" },
  editorInput: {
    flex: 1, background: "rgba(20,22,26,.9)", color: "#F4E9D2",
    border: "1px solid rgba(255,255,255,.14)", borderRadius: 6,
    padding: "6px 8px", fontSize: 13,
  },
  editorFooter: {
    display: "flex", justifyContent: "flex-end", gap: 10,
    padding: "12px 18px", borderTop: "1px solid rgba(255,255,255,.1)",
  },
  editorCancel: {
    background: "transparent", color: "#EDEAE3",
    border: "1px solid rgba(255,255,255,.18)", borderRadius: 8,
    padding: "9px 16px", fontSize: 13, cursor: "pointer",
  },
  editorApply: {
    border: "none", borderRadius: 8, padding: "9px 18px",
    fontSize: 13, fontWeight: 700, cursor: "pointer",
  },
};
